# .github/workflows/scrape_scholar.yml

name: Google Scholar Scraper

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: 'Search keywords for Google Scholar (e.g., triatomine United States)'
        required: true
        default: 'triatomine United States'
        type: string
      start_year:
        description: 'Start year for publications (e.g., 2022)'
        required: true
        default: 2022
        type: number
      end_year:
        description: 'End year for publications (e.g., 2024)'
        required: true
        default: 2024
        type: number
      output_filename:
        description: 'Path and filename for the output CSV (e.g., north_america_triatomine/google_scholar_raw_US.csv)'
        required: true
        default: 'north_america_triatomine/google_scholar_raw_US.csv'
        type: string

jobs:
  scrape-scholar-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip # Ensure pip is up-to-date
          # Upgrade scholarly, httpx, and pandas to their latest compatible versions
          pip install --upgrade scholarly httpx pandas
          # Optional: Add this step for debugging if issues persist
          # pip freeze

      - name: Create output directory if it doesn't exist
        run: |
          mkdir -p $(dirname ${{ github.event.inputs.output_filename }})

      - name: Run Google Scholar Scraper Script
        env:
          INPUT_KEYWORDS: ${{ github.event.inputs.keywords }}
          INPUT_START_YEAR: ${{ github.event.inputs.start_year }}
          INPUT_END_YEAR: ${{ github.event.inputs.end_year }}
          INPUT_OUTPUT_FILENAME: ${{ github.event.inputs.output_filename }}
        run: python scripts/scholar_scraper.py # Adjust script path if different

      - name: Upload generated CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-scholar-results-csv
          path: ${{ github.event.inputs.output_filename }}
          retention-days: 7
